config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :songs
  resources :votes, only: [:new, :create, :destroy]
  match '/register', to: 'users#new', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'
  match '/auto', to: 'pages#autopopulate', via: 'get'
  match '/vote', to: 'votes#new', via: 'get'
  match '/results', to: 'pages#results', via: 'get'
  match '/add_votes', to: 'pages#add_votes', via: 'get'
  post "/playlist" => "pages#playlist"

end

app/models/song.rb
class Song < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order('created_at DESC') }
	before_validation { self.spotify_id = spotify_id.gsub(/(.)*\//, '') }
	validates :spotify_id, presence: true, length: { minimum: 1 }, uniqueness: true
	validates :user_id, presence: true
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	before_action :signed_in_user, only: [:index, :edit, :update, :destroy, :show]

	def index
		@songs = Song.all
		@votes = Vote.all
	end

	def new
		@song = Song.new
	end	
	
	def create
		standard_user = User.find_by(email: "gabe@duckbrigade.com")
		@song = standard_user.songs.build(song_params)
		if @song.save
			url = 'https://api.spotify.com/v1/tracks/' + @song.spotify_id
			resp = HTTParty.get(url)
			if resp['name']
				artist = resp['artists'][0]['name']
				title = resp['name']
				album = resp['album']['name']
				artwork_url = resp['album']['images'][1]['url']
				preview_url = resp['preview_url']
				@song.update_attributes(:artist => artist, :title => title, :album => album, :artwork_url => artwork_url, :preview_url => preview_url)
				flash[:success] = artist + ' - ' + title + ' has been added to BSW.'
			else
				flash[:danger] = 'Song could not be added'
				@song.destroy
			end
			redirect_to new_song_path
		else
			render 'new'
		end
	end

	def edit
		@song = Song.find(params[:id])
	end

	def update
		@song = Song.find(params[:id])

		if @song.update(song_params)
			redirect_to @song
		else
			render 'edit'
		end
	end
	
	def show
		@song = Song.find(params[:id])
	end

	def destroy
		@song = Song.find(params[:id])
		@song.destroy

		redirect_to songs_path
	end

	private
		def song_params
			params.require(:song).permit(:spotify_id)
		end

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_song.html.erb
<tr>
  <td><%= song.title %></td>
  <td><%= song.artist %></td>
  <td><%= song.album %></td>
  <td><%= song.spotify_id %></td>
  <td><a href="<%= song.preview_url %>">Preview</a></td>
  <% votes_for = @votes.where(:for_id => song).count %>
  <% votes_against = @votes.where(:against_id => song).count %>
  <% total_votes = votes_for + votes_against %>
  <td><%= votes_for %></td>
  <td><%= votes_against %></td>
  <td>
  <% if total_votes == 0 %>
	0%
  <% else %>
  	<%= ((votes_for.to_f / total_votes.to_f) * 100).to_i %>%
  <% end %>
  </td>
  <td><%= link_to '<i class="fa fa-trash"></i><span class="sr-only">Delete</span>'.html_safe, song_path(song), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/songs/index.html.erb
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>	

<h1>Songs</h1>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Artist</th>
    <th>Album</th>
    <th>Spotify ID</th>
    <th>Preview</th>
    <th>+1</th>
    <th>-1</th>
    <th>Score</th>
    <th>Delete</th>
  </tr>
 
  <%= render @songs %>
</table>

<h3>Autopopulate Songs</h3>
<p>
	<a href="/auto?by=gabe" class="btn btn-primary">Gabe's Picks</a>
	<a href="/auto?by=most_streamed" class="btn btn-primary">Most Streamed</a>
	<a href="/auto?by=most_viral" class="btn btn-primary">Most Viral</a>
</p>

app/views/songs/new.html.erb
<h1>Add Song</h1>

<%= form_for @song do |f| %>
	<% if @song.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= pluralize(@song.errors.count, "error") %> prohibited
	      this song from being added:</h2>
	    <ul>
	    <% @song.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>
	<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
  	<% end %>	
	<p>
		<%= f.label :spotify_id, class: "control-label sr-only"  %>
	<%= f.text_field :spotify_id, class: 'form-control', placeholder: 'Spotify Track ID or URL' %>
	</p>
	<p>
	<%= f.submit 'Submit', {class: 'btn btn-primary'} %>
	</p>
<% end %>

<h1>Add Playlist</h1>

<form action="/playlist" method="post">
	<p>
		<input type="text" class="form-control" name="playlist" placeholder="Add a Spotify Playlist URL">
	</p>
	<p>
		<input type="submit" class="btn btn-primary" value="Submit">
	</p>
</form>