config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :songs
  resources :votes, only: [:new, :create, :destroy]
  match '/register', to: 'users#new', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'
  match '/auto', to: 'pages#autopopulate', via: 'get'
  match '/vote', to: 'votes#new', via: 'get'
  match '/results', to: 'pages#results', via: 'get'
  match '/add_votes', to: 'pages#add_votes', via: 'get'
  post "/playlist" => "pages#playlist"

end

app/views/pages/index.html.erb
<div class="record-header">
	<h1 class="sr-only">Best Song in the World</h1>
	<%= image_tag "label.svg", width: 469, height: 469, class: "record-label paused" %>
	<%= link_to "Add a Song", new_song_path, class: "newsong" %>
</div>
<div class="row">
	<div class="box-outer-3">
		<div class="box-outer-2">
			<div class="box-outer clearfix">
				<div class="col-xs-6 text-center">
					<div class="songbox">
						<div class="songbox-image">
							<img src="<%= @song1.artwork_url %>" width="300" class="song-image">
						</div>
						<audio src="<%= @song1.preview_url %>" class="song"></audio><br>
						<span class="song-title"><%= @song1.title %></span><br>
						<span class="song-artist"><%= @song1.artist %></span><br>
					</div>
					<%= link_to "This Song is Better", new_vote_path(:winner => 0, :song1 => @song1.id, :song2 => @song2.id), class: "btn btn-lg btn-primary" %>						
				</div>
				<div class="col-xs-6 text-center">
					<div class="songbox">
						<div class="songbox-image">
							<img src="<%= @song2.artwork_url %>" width="300" class="song-image">
						</div>
						<audio src="<%= @song2.preview_url %>" class="song"></audio><br>
						<span class="song-title"><%= @song2.title %></span><br>
						<span class="song-artist"><%= @song2.artist %></span><br>
					</div>
					<%= link_to "This Song is Better", new_vote_path(:winner => 1, :song1 => @song1.id, :song2 => @song2.id), class: "btn btn-lg btn-primary" %>						
				</div>
			</div>
		</div>
	</div>
</div>
<%= audio_tag("BESTSONGINTRO.mp3", id: "themesong") %>

app/views/pages/results.html.erb
<div class="record-header">
	<h1 class="sr-only">Best Song in the World</h1>
	<%= image_tag "label-reverse.svg", width: 469, height: 469, class: "record-label paused" %>
</div>
<div class="row">
	<div class="box-outer-4">
		<div class="box-outer-3">
			<div class="box-outer-2">
				<div class="box-outer clearfix">
					<div class="col-xs-6 text-center">
						<% if @winner == '0' %>
							<div class="winnerbox outlinebox">
						<% elsif @winner == '1' %>
							<div class="loserbox outlinebox">
						<% end %>
							<div class="songbox">
								<div class="songbox-image">
									<img src="<%= @song1.artwork_url %>" width="300">
								</div>
								<audio src="<%= @song1.preview_url %>" class="song"></audio>
								<div class="songchart"><%= pie_chart [["For", @votes_for_1], ["Against", @votes_against_1]], colors: ["white", "black"], library: {fontSize: 0, backgroundColor: 'black', legend: {position: 'none'}} %></div>
							</div>
							<% if @winner == '0' %>
								<h3>Winner</h3>
							<% elsif @winner == '1' %>
								<h3>Loser</h3>
							<% end %>
							</div>
							<span class="score">
								<span class="song-artist"><%= @song1.artist %> - <%= @song1.title %></span><br>
								<span class="score-title">Score</span><br>
								<span class="score-number"><%= @percentage_1 %></span><span class="score-pct">%</span>
							</span>
					</div>
					<div class="col-xs-6 text-center">
						<% if @winner == '0' %>
							<div class="loserbox outlinebox">
						<% elsif @winner == '1' %>
							<div class="winnerbox outlinebox">
						<% end %>
							<div class="songbox">
								<div class="songbox-image">
									<img src="<%= @song2.artwork_url %>" width="300">
								</div>
								<audio src="<%= @song2.preview_url %>" class="song"></audio>
								<div class="songchart"><%= pie_chart [["For", @votes_for_2], ["Against", @votes_against_2]], colors: ["white", "black"], library: {fontSize: 0, backgroundColor: 'black', legend: {position: 'none'}} %></div>
							</div>
							<% if @winner == '1' %>
								<h3>Winner</h3>
							<% elsif @winner == '0' %>
								<h3>Loser</h3>
							<% end %>
							</div>
							<span class="score">
								<span class="song-artist"><%= @song2.artist %> - <%= @song2.title %></span><br>
								<span class="score-title">Score</span><br>
								<span class="score-number"><%= @percentage_2 %></span><span class="score-pct">%</span>
							</span>
					</div>
					<div class="col-xs-12 text-center">
						<%= link_to "Play Again", root_path, class: 'btn btn-primary' %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<%= audio_tag("BESTSONGOUTRO.mp3", id: "themesong") %>